name: Test deployment scripts

'on':
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55  # v5.5.0
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r deployment/requirements.txt

      - name: Check Astropy Librarian installation
        run: |
          astropylibrarian --help

      - name: Install tutorials into site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p public/tutorials
          python deployment/installtutorials.py --dest public/tutorials

      - name: List tutorials
        run: |
          tree public/tutorials
