name: Test deployment scripts

'on':
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install pip==23.3.2
          python -m pip install -r deployment/requirements.txt

      - name: Check Astropy Librarian installation
        run: |
          astropylibrarian --help

      - name: Download latest tutorials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python deployment/installtutorials.py --dest public/tutorials

      - name: List tutorials
        run: |
          tree public
